### ISSUE TITLE
Resign first responder issue

### ISSUE THREAD

**Issue by bhavinbhadani-ril** [vitalybatrakov/BottomSheet#4]
On resign first responder, whole view is hidden because it's y position is the same as screen height on resign.

**Comment by vitalybatrakov** [comment]
Sorry, I don't quite understand the issue here. Could you elaborate a bit more?

**Comment by bhavinbhadani-ril** [comment]
Yes, there are 2 issues.

1. On view did load of controller, when I add becomeFirstResponder and remove that responder afterwards, the containerView frame changes along with keyboard
2. How to resize presented view frame along with container view constraint change?

**Comment by vitalybatrakov** [comment]
1. Can you please provide the controller code example to reproduce the issue?
2. If you want to change presented view size after transition is completed, you can simply change the view frame to the new one from view controller like this:
```
UIView.animate(withDuration: 0.25) { // animate if needed
      self.view.frame = newFrame
}
```

**Comment by bhavinbhadani-ril** [comment]
1. It's resolved now as I add textfield responder to did appear.
2. Yes. Thanks

**Comment by bhavinbhadani-ril** [comment]
But one more thing. content size is not calculated correctly and because of that some labels take more height than it should.

check this title size. It's not sized to fit as it should here,

<img width="417" alt="Screenshot 2024-10-03 at 6 24 52 PM" src="https://github.com/user-attachments/assets/5433efac-70c7-4438-9bd8-623212c9b79b">

<img width="335" alt="Screenshot 2024-10-03 at 6 25 53 PM" src="https://github.com/user-attachments/assets/88b56a04-a609-44df-a5c8-f2020620de89">

**Comment by bhavinbhadani-ril** [comment]
@vitalybatrakov  One more thing. How does it automatically updates the view height change like If I have stack view with hidden element and now I unhide it and wants presented view to adjust height, how does it possible?

**Comment by vitalybatrakov** [comment]
> @vitalybatrakov One more thing. How does it automatically updates the view height change like If I have stack view with hidden element and now I unhide it and wants presented view to adjust height, how does it possible?

after transition completed if you change stackView structure inside presented view so it height is changed, presented view will not update frame automatically. You will have to update frame manually like in code I shared above.
